import axios from 'axios';

import {
  LISTAR_TIPOS_NOTIFICACIONES,
  VER_TIPO_NOTIFICACION,
  INSERTAR_TIPO_NOTIFICACION,
  ELIMINAR_TIPO_NOTIFICACION,
  ERROR_INSERTAR_TIPO_NOTIFICACION,
  ERROR_ACTUALIZAR_TIPO_NOTIFICACION,
  ERROR_ELIMINAR_TIPO_NOTIFICACION,
  ERROR_LISTAR_TIPOS_NOTIFICACIONES,
  SUCCESSFULL_INSERT_TIPO_NOTIFICACION,
  SUCCESSFULL_UPDATE_TIPO_NOTIFICACION,
  SUCCESSFULL_DELETE_TIPO_NOTIFICACION
} from '../constants/tiponotificacion.js';

import {
  
} from '../constants/api';