/**
 * Estados del reducer
 */
export const VER_EVENTO = 'VER_EVENTO';
export const INSERTAR_EVENTO = 'INSERTAR_EVENTO';
export const ELIMINAR_EVENTO = 'ELIMINAR_EVENTO';
export const LISTAR_EVENTOS = 'LISTAR_EVENTOS';

/**
 * Estados del API
 */
export const ERROR_INSERTAR_EVENTO = 'ERROR_INSERTAR_EVENTO';
export const ERROR_ACTUALIZAR_EVENTO = 'ERROR_ACTUALIZAR_EVENTO';
export const ERROR_ELIMINAR_EVENTO = 'ERROR_ELIMINAR_EVENTO';
export const ERROR_LISTAR_EVENTO = 'ERROR_LISTAR_EVENTO';

export const SUCCESSFULL_INSERT_EVENTO = 'SUCCESSFULL_INSERT_EVENTO';
export const SUCCESSFULL_UPDATE_EVENTO = 'SUCCESSFULL_UPDATE_EVENTO';
export const SUCCESSFULL_DELETE_EVENTO = 'SUCCESSFULL_DELETE_EVENTO';
