
/*
	Estados del reducer
*/
export const VER_TIPO_ACTIVIDAD = 'VER_TIPO_ACTIVIDAD';
export const INSERTAR_TIPO_ACTIVIDAD = 'INSERTAR_TIPO_ACTIVIDAD';
export const ELIMINAR_TIPO_ACTIVIDAD = 'ELIMINAR_TIPO_ACTIVIDAD';
export const LISTAR_TIPOS_ACTIVIDADES = 'LISTAR_TIPOS_ACTIVIDADS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_TIPO_ACTIVIDAD = 'ERROR_INSERTAR_TIPO_ACTIVIDAD';
export const ERROR_ACTUALIZAR_TIPO_ACTIVIDAD = 'ERROR_ACTUALIZAR_TIPO_ACTIVIDAD';
export const ERROR_ELIMINAR_TIPO_ACTIVIDAD = 'ERROR_ELIMINAR_TIPO_ACTIVIDAD';
export const ERROR_LISTAR_TIPOS_ACTIVIDADES = 'ERROR_LISTAR_TIPOS_ACTIVIDADS';
export const ERROR_TIPO_ACTIVIDAD = 'ERROR_TIPO_ACTIVIDAD';

export const SUCCESSFULL_INSERT_TIPO_ACTIVIDAD = 'SUCCESSFULL_INSERT_TIPO_ACTIVIDAD';
export const SUCCESSFULL_UPDATE_TIPO_ACTIVIDAD = 'SUCCESSFULL_UPDATE_TIPO_ACTIVIDAD';
export const SUCCESSFULL_DELETE_TIPO_ACTIVIDAD = 'SUCCESSFULL_DELETE_TIPO_ACTIVIDAD';